### ISSUE TITLE
Initial score of a new destination

### ISSUE THREAD

**Issue by thanelmas** [ensozos/iTravel#3]
When adding a new destination, the initial score of it should be 10. 
However, when we click on the destination and see the DestinationView, the score is 0 (this is wrong) and only when we press "Save" the score becomes 10 (as it should be from the beginning).

**Comment by ensozos** [comment]
Δεν ειναι και σωστό  όμως   να ξεκινήσει  με 10 .Κανονικά  θα έπρεπε να ελέγχουμε απο το ιστορικό με τους προορισμούς  και να μην υπάρχει  αυτη η ερωτηση .

**Comment by ensozos** [comment]
'Εχω κανει το initial score να ξεκινάει στα 10
